/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ABreadcrumb: typeof import('ant-design-vue/es')['Breadcrumb']
    ABreadcrumbItem: typeof import('ant-design-vue/es')['BreadcrumbItem']
    AButton: typeof import('ant-design-vue/es')['Button']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    APopconfirm: typeof import('ant-design-vue/es')['Popconfirm']
    Aside: typeof import('./src/components/Layout/Aside/index.vue')['default']
    Breadcrumb: typeof import('./src/components/Layout/Breadcrumb/index.vue')['default']
    Header: typeof import('./src/components/Header/index.vue')['default']
    Icon: typeof import('./src/components/Icon/index.vue')['default']
    Layout: typeof import('./src/components/Layout/index.vue')['default']
    Logo: typeof import('./src/components/Layout/Logo/index.vue')['default']
    Menu: typeof import('./src/components/Layout/Menu/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Top: typeof import('./src/components/Layout/Top/index.vue')['default']
    UserInfo: typeof import('./src/components/Layout/Top/UserInfo.vue')['default']
  }
}
